services:
  - type: web
    name: campusly-api
    env: node
    rootDir: campuss-api
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
